# Generated by Django 3.0.4 on 2020-03-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200311_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
